# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    displayName: "Choose ENV"
    type: string
    default: "dev"
    values:
      - dev
      - prod
      - qa

variables: 
  - name: imagename
    value: appogin

stages:
  - stage: Build
    displayName: "Build Application"
    jobs:
      - job: MavenBuild
        steps:
          - task: Maven@4
            inputs:
               mavenPomFile: "pom.xml"
               goals: "clean package"

  - stage: DockerBuildPush
    dependsOn: build
    jobs:
      - job: Docker
        steps:
          - task: Docker@2
            inputs:
              containerRegistry:  'AzureCR-serviceconnection'
              repository: "$(imageName)"
              command: "buildAndPush"
              Dockerfile: '**/Dockerfile'
              
  - stage: Deploy
    displayName: "Deploy to AKS"
    dependsOn: Docker
    jobs:
      - deployment: DeployApp
        environment: ${{parameters.environment}}
        strategy:
         runOnce:
           deploy:
             steps:
               - task: Kubernetes@1
                 inputs:
                   connectionType: Azure Resource Manager
                   azureSubscriptionEndpoint:  "Azure-ServiceConnection"
                   azureResourceGroup: "rg-${{parameters.environment }}"
                   kubernetesCluster: "aks-${{parameters.environment }}"
                   command: apply
                   useConfigurationFile:  true



