trigger:
  branches:
    include:
      - main

parameters:
  - name: environment
    displayName: "Choose ENV"
    type: string
    default: "dev"
    values:
      - dev
      - prod
      - qa

variables: 
  - name: imagename
    value: appogin

pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    displayName: "Build Application"
    jobs:
      - job: MavenBuild
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: "pom.xml"
              goals: "clean package"

  - stage: DockerBuildPush
    dependsOn: Build
    jobs:
      - job: Docker
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'AzureCR-serviceconnection'   # Docker Registry connection
              repository: "$(imagename)"
              command: "buildAndPush"
              Dockerfile: '**/Dockerfile'

  - stage: Deploy
    displayName: "Deploy to AKS"
    dependsOn: DockerBuildPush
    jobs:
      - deployment: DeployApp
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Kubernetes@1
                  inputs:
                    connectionType: Azure Resource Manager
                    azureSubscriptionEndpoint: 'Zomato-ARG'   # 👈 ARM connection, not Docker
                    azureResourceGroup: "rg-${{ parameters.environment }}"
                    kubernetesCluster: "aks-${{ parameters.environment }}"
                    command: apply
                    useConfigurationFile: true
                    configuration: 'manifests/deployment.yaml'
